 <br><br><br><br><br><br>
 <div class="row">
    <div class="col-sm">
     
    </div>
    <div class="col-sm">
<form action="" method="post" enctype="multipart/form-data">
	<input type="hidden"  name="profileId"  value="<?php echo $profile->id;?>">
  <div class="form-group">
    <label>Email address</label>
    <input type="email" name="email" class="form-control" id="email"   required value="<?php echo $profile->username?>">
  </div>
  
  <div class="form-group">
    <label>Firstname</label>
    <input type="text" name="firstname" class="form-control" id="firstname"   required value="<?php echo $profile->first_name?>"> 
  </div>
  
   <div class="form-group">
    <label>Picture</label>
    <div class="custom-file">
          <input type="file" name="photo"  class="custom-file-input"  >
          <label class="custom-file-label" >Choose file</label>
    </div>
  </div>
  <?php if($profile->picture!=''){?>
   <div class="form-group">  
          <img style="width:100px; height:100px" src="<?php echo $this->url->getBaseUri().'public/img/'.$profile->picture; ?>">
  </div>
  <?php }?>
  <button type="submit" class="btn btn-info">Submit</button>
  
  <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  
  <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <ul class="timeline">
              <li>
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="img/about/5.jpg" alt="">
                  
                  <br><br>
                 <center>
                 
                  Saharat Buarawong
                  590610670
                
                  </center>
                </div>
            </ul>
          </div>
        </div>
      </div>
    </section>

</form>
    </div>
    <div class="col-sm">
    </div>
  </div>